#+TITLE: my-memacs-config
#+PROPERTY: header-args :tangle elisp.ls

* Table of Contents                                                     :TOC:
- [[#prerequisites][Prerequisites]]
- [[#installation][Installation:]]
  - [[#macos][macos]]
  - [[#ai][AI]]
  - [[#elisp-examples][elisp examples:]]
  - [[#how-to-tangle-the-code-blocks][How to tangle the code blocks]]

* Prerequisites

Install the python LSP server:

#+begin_src bash :tangle no
pip install 'python-lsp-server[all]'
#+end_src

Install Java LSP server:

When the java-lsp module asks for to install the language server say 'y' and
enter 'jdtls' if it prompts for the language server name.

Install the language server via brew:
#+begin_src 
 brew install jdtls
#+end_src

For ellama you need a local LLM running:

#+begin_src bash :tangle no
brew install ollama
#+end_src

Use the Zephyr model:
#+begin_src bash :tangle no
ollama pull zephyr
#+end_src

* Installation:

#+begin_src bash :tangle no
make
#+end_src

** macos

*** ITerm2

Q: How do I make the option/alt key act like Meta or send escape codes?
A: Go to Preferences > Profiles tab. Select your profile on the left, and then open the Keyboard tab. At the bottom is a set of buttons that lets you select the behavior of the Option key. For most users, Esc+ will be the best choice.

** AI

*** Github Copilot

https://github.com/copilot-emacs/copilot.el

Install copilot language server
#+begin_src bash :tangle no
npm install -g @github/copilot-language-server
#+end_src

** elisp examples:

Getting the Emacs version

say hello

#+begin_src emacs-lisp
(message "Hello, World!")
#+end_src

#+RESULTS:
: Hello, World!


For more see [[[[file:doc/elisp.org]]]]

** How to tangle the code blocks

#+begin_src bash :tangle no
emacs --batch README.org  -f org-babel-tangle
#+end_src

#+RESULTS:
